### ISSUE TITLE
Error reported by running sh command line

### ISSUE THREAD

**Issue by wangdazhong1112** [hyer/HDFormer#2]
When I tried to use the run.sh command line, I just ran it and output the file, and didn't start training. The file structure is as follows
![image](https://user-images.githubusercontent.com/119930848/223302268-fa738d06-ed20-4e42-9cda-8c8e7aea7ee4.png)
![image](https://user-images.githubusercontent.com/119930848/223302305-d44fca4e-6bf2-4fc5-b7f7-1359e9322da9.png)
![image](https://user-images.githubusercontent.com/119930848/223302351-608c0011-6e1c-45d1-9f74-c7bd692497ae.png)

**Comment by StupidAdam** [comment]
It seems the author forget giving us the train.h5, test.h5, as well as camera.h5 files and those needed datasets.

**Comment by hyer** [comment]
Sorry for late reply. We will update the repository later. Since the Human3.6M dataset need licenses, the developer should apply for authorisation from [Human3.6M](http://vision.imar.ro/human3.6m/description.php). If you have any other question, you can send me an email.

**Comment by hyer** [comment]
We have update the repository and release the pre-trained model of Human3.6M with 2D GT input, which can be found in `checkpoints/model`. If you don't have idea about the dataset preprocessing, you can send me an email.

**Comment by jianlai123-123** [comment]
Hello, can you run it now? I encountered a problem running. Can you give me some guidance? thank you. 
<img width="720" alt="21" src="https://user-images.githubusercontent.com/117512033/233261153-4f6573c2-7283-42f9-a3aa-a69adf15bd33.png">

@wangdazhong1112
